#!/bin/bash
# stop if not on master branch of local git repo
git branch | awk '$1~/\*/{if($2~/main/){exit 0}else{exit 1}}'
if [ $? -ne 0 ]; then
    echo "STOP: not on main branch of local git repo"
    exit 1
fi
# synchronize local git repo with central GitHub repo
git fetch upstream
git merge upstream/main
git push origin main
exit 0
