package:
  name: taxcalc
  version: 0.0.0

requirements:
  build:
    - python >=3.6.5,<3.7
    - numpy >=1.12.1
    - pandas >=0.22.0
    - numba
    - toolz

  run:
    - python >=3.6.5,<3.7
    - numpy >=1.12.1
    - pandas >=0.22.0
    - numba
    - toolz

about:
  home: http://www.github.com/TPRU-demo
